# Copyright 2024 NetCracker Technology Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if and .Values.prometheusAdapter.install .Values.prometheusAdapter.tlsEnabled }}
{{- if not (and .Values.prometheusAdapter.tlsConfig.caSecret .Values.prometheusAdapter.tlsConfig.certSecret .Values.prometheusAdapter.tlsConfig.keySecret) }}
{{- if and (not .Values.prometheusAdapter.tlsConfig.existingSecret) .Values.prometheusAdapter.tlsConfig.generateCerts .Values.prometheusAdapter.tlsConfig.generateCerts.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-adapter-client-tls-certificate
  labels:
    app.kubernetes.io/name: prometheus-adapter-client-tls-certificate
    app.kubernetes.io/instance: {{ cat "prometheus-adapter-client-tls-certificate-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: prometheus-adapter
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  secretName: {{ default "prometheus-adapter-client-tls-secret" .Values.prometheusAdapter.tlsConfig.generateCerts.secretName }}
  duration: {{ default 365 .Values.prometheusAdapter.tlsConfig.generateCerts.duration | mul 24 }}h
  renewBefore: {{ default 15 .Values.prometheusAdapter.tlsConfig.generateCerts.renewBefore | mul 24 }}h
  commonName: prometheus-adapter-client-tls-certificate-crt
  isCA: false
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
    - localhost
    - prometheus-adapter.{{ .Release.Namespace }}.svc
  ipAddresses:
    - 127.0.0.1
  issuerRef:
    name: {{ .Values.prometheusAdapter.tlsConfig.generateCerts.clusterIssuerName }}
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}
{{- end }}
{{- end }}
