# Copyright 2024 NetCracker Technology Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# RBAC settings
role:
  install: true
roleBinding:
  install: true
clusterRole:
  install: true
clusterRoleBinging:
  install: true

# Operation settings
nameOverride: "qubership-prometheus-adapter-operator"
fullnameOverride: "qubership-prometheus-adapter-operator"

image: "ghcr.io/netcracker/qubership-prometheus-adapter-operator:main"

annotations:
  test.annotation/key: test-value
labels:
  test.label/key: test-value

securityContext:
  runAsUser: 2001
  fsGroup: 2001
resources:
  requests:
    cpu: 10m
    memory: 50Mi
  limits:
    cpu: 50m
    memory: 100Mi

nodeSelector:
  node: primary
tolerations:
  - key: "key"
    operator: "Equal|Exists"
    value: "value"
    effect: "NoSchedule|PreferNoSchedule|NoExecute(1.6 only)"


# Adapter settings
prometheusAdapter:
  # Deployment settings
  image: "ghcr.io/netcracker/qubership-prometheus-adapter:main"
  replicas: 1

  annotations:
    test.annotation/key: test-value
  labels:
    test.label/key: test-value

  securityContext:
    runAsUser: 2001
    fsGroup: 2001
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 1000m
      memory: 1Gi

  affinity:
    podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - prometheus-adapter
        topologyKey: kubernetes.io/hostname
  nodeSelector:
    node: primary
  tolerations:
    - key: "key"
      operator: "Equal|Exists"
      value: "value"
      effect: "NoSchedule|PreferNoSchedule|NoExecute(1.6 only)"

  # Adapter/Prometheus settings
  metricsRelistInterval: "1m"
  prometheusUrl: "http://prometheus-operated.monitoring.svc:9090"
  customScaleMetricRulesSelector:
    matchLabels:
      app.kubernetes.io/component: monitoring
